### ISSUE TITLE
Error invalid_grant on sending command to device

### ISSUE THREAD

**Issue by jorgemontalvao** [GoogleCloudPlatform/nodejs-docs-samples#1348]
I am copying and pasting the code here and there is no compilation issue. I just got the needed from the sample. I am not sure if I miss some pre-deployment step. https://cloud.google.com/iot/docs/how-tos/commands#iot-core-send-command-nodejs

But it failed with error "invalid_grant".

First, I installed google-cloud/iot and I am using the last supported version:

npm i @google-cloud/iot -- ok

npm version: 6.4.1

node.jo version: v8.13.0

firebase version: 6.11.0

win10 pro

If I run gcloud command it works fine

gcloud iot devices commands send \
    --command-data="Hello device" \
    --region=us-central1  \
    --registry=device001-registry \
    --device=device001-dev

This is the console log. 

i  functions: Finished "sendCommandToDevice" in ~1s
>  { Error: Getting metadata from plugin failed with error: invalid_grant
>      at Http2CallStream.call.on (D:\Jorge\test01\node_modules\
>      at emitOne (events.js:121:20)
>      at Http2CallStream.emit (events.js:211:7)
>      at Http2CallStream.endCall (D:\Jorge\test01\node_modules\
>      at D:\Jorge\test01\node_modules\@grpc\grpc-js\build\src\c
>      at <anonymous>
>      at process._tickCallback (internal/process/next_tick.js:189:7)
>    code: '400',
>    details: 'Getting metadata from plugin failed with error: invalid_grant',
>    metadata: Metadata { options: undefined, internalRepr: Map {} },
>    note: 'Exception occurred in retry method that was not classified as transient' }

**Comment by fhinkel** [comment]
@jorgemontalvao thanks for raising the issue! 
@hongalex Could you have a look at this IoT problem. Thank you!

**Comment by jorgemontalvao** [comment]
I think some "google-cloud" package is not supported on localhost.

For example, PubSub triggers:

```
export.<function_name> = 
  functions.pubsub.topic('<topic_name>').onPublish((message, context) => {})
```

this generates the message below:

> Ignoring trigger "<function_name>" because the service "pubsub.googleapis.com" is not yet supported.

In addition, I added google-cloud dependencies in package.json, and **it works well only in the cloud.**
```
  "dependencies": {
    "@google-cloud/iot": "^1.0.0",
    "@google-cloud/pubsub": "^0.28.0",
    "googleapis": "^40.0.0"
  }
```

**Comment by fhinkel** [comment]
Thanks for clarifying. @ace-n this looks like a functions issue. Can you have a look please?

**Comment by ace-n** [comment]
@jorgemontalvao FYI - GCF doesn't support *on-publish* triggers as an event type.

(The trigger you are using is through the client library, not GCF itself - and only runs if a valid GCF event causes the function to be invoked, such as *receiving* a Pub/Sub message.)

Also - what dependency errors are you getting? (Can you include the error message + stack trace?)

**Comment by fhinkel** [comment]
Closing this due to inactivity. Please let us know if we should reopen it. Thanks!
