### ISSUE TITLE
Not able to run Cloud Healthcare API to store a DICOM instance(dicomWebStoreInstance.js)

### ISSUE THREAD

**Issue by nehawankar174** [GoogleCloudPlatform/nodejs-docs-samples#1521]
Hello,
I am trying to run DICOMweb example file - **dicomWebStoreInstance.js** by passing the required parameters via below command:

` node dicomWebStoreInstance.js <projectId> <cloudRegion> <datasetId> <dicomStoreId> <dcmFile>`

but its giving following error:

`(node:9204) UnhandledPromiseRejectionWarning: Error: [object Object]
    at Gaxios.request (D:\project\neuradetect\server\node_modules\gaxios\build\src\gaxios.js:70:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:9204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code`

Any help regarding this would be greatly appreciated!

**Comment by fhinkel** [comment]
:wave: @nehawankar174 Thanks for reporting the issues. @nnegrey, could you have a look at this? Thank you

**Comment by noerog** [comment]
Can you make sure that you're using a valid DICOM file? You could try using one of the files in the public datasets offered by the Healthcare API (https://cloud.google.com/healthcare/docs/resources/public-datasets/).

If that doesn't work, can you edit the D:\project\neuradetect\server\node_modules\gaxios\build\src\gaxios.js file to print out the error in the catch (e) block at line 74? That error will help with debugging.

**Comment by fhinkel** [comment]
I'm closing this due to inactivity. Please re-open if you still run into this issue.

**Comment by nehawankar174** [comment]
Hey noerog,
Sorry for inactivity. I am re-opening this issue as I am still facing the same.

I was trying to call WebStore API by using one of the files in the public datasets offered by the Healthcare API (_https://cloud.google.com/healthcare/docs/resources/public-datasets/_) but in that case I don't have permissions to access **Public Datasets**. I have attached the screenshot for the same.
![permission_denied](https://user-images.githubusercontent.com/39078864/68853449-0431fa00-0700-11ea-8448-600af1a19cef.PNG)
Could you please guide me to get permissions to access public datasets?

Thanks

**Comment by pkling** [comment]
Are you trying to access the dataset via GCS or via the Cloud Healthcare API?

For GCS access, no special permissions are required (you can authenticate with any Google account).

For CHC API access, please request access here: https://services.google.com/fb/forms/cloudhealthcarepublicdatasetaccess/

Thanks

Patrick

**Comment by nehawankar174** [comment]
@Patrick, Yes I am trying to access the dataset via Cloud Healthcare API.
And as per your suggestion I have requested for the access CHC API.

Thanks,
Neha

**Comment by fhinkel** [comment]
Looks like you were able to resolve the issue. Let us know if that wasn't the case and we're happy to re-open the issue.
