### ISSUE TITLE
Error: Cannot find module '/srv/index.js'

### ISSUE THREAD

**Issue by gjcassiano** [GoogleCloudPlatform/nodejs-docs-samples#1830]
I build and deploy the application at GAE 

Could help-me?

`Error: Cannot find module '/srv/index.js' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) at Function.Module._load (internal/modules/cjs/loader.js:562:25) at Function.Module.runMain (internal/modules/cjs/loader.js:831:12) at startup (internal/bootstrap/node.js:283:19) at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)`

![image](https://user-images.githubusercontent.com/13663730/82720229-5a6b9100-9c7f-11ea-9066-028baaa2133f.png)

**Comment by gjcassiano** [comment]
I resolve that removing the *.js from .gcloudignore file
