### ISSUE TITLE
Update datastore dependency fails

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#1844]
See https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1839

**Comment by BenWhitehead** [comment]
Looks like we need to bump the env to be node 10+ instead of 8

<details>
  <summary>failure log</summary>

```
Status: Downloaded newer image for gcr.io/cloud-devrel-kokoro-resources/node:8-user
Executing: docker run --rm --interactive --network=host --privileged --volume=/var/run/docker.sock:/var/run/docker.sock --workdir=/tmpfs/src --entrypoint=github/nodejs-docs-samples/.kokoro/build.sh --env-file=/tmpfs/tmp/tmp0dw91rvm/envfile --volume=/tmpfs:/tmpfs gcr.io/cloud-devrel-kokoro-resources/node:8-user
/tmpfs/src/github/nodejs-docs-samples /tmpfs/src
/tmpfs/src

> protobufjs@6.9.0 postinstall /tmpfs/src/github/nodejs-docs-samples/datastore/functions/node_modules/protobufjs
> node scripts/postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for @google-cloud/datastore@6.0.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: @google-cloud/datastore@6.0.0
npm WARN notsup Unsupported engine for @google-cloud/promisify@2.0.1: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: @google-cloud/promisify@2.0.1
npm WARN notsup Unsupported engine for google-gax@2.6.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: google-gax@2.6.0
npm WARN notsup Unsupported engine for google-auth-library@6.0.1: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: google-auth-library@6.0.1
npm WARN notsup Unsupported engine for gaxios@3.0.3: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: gaxios@3.0.3
npm WARN notsup Unsupported engine for gcp-metadata@4.1.0: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: gcp-metadata@4.1.0
npm WARN notsup Unsupported engine for gtoken@5.0.1: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: gtoken@5.0.1
npm WARN notsup Unsupported engine for google-p12-pem@3.0.1: wanted: {"node":">=10"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: google-p12-pem@3.0.1
npm WARN notsup Unsupported engine for @google-cloud/functions-framework@1.5.1: wanted: {"node":">=10.0.0"} (current: {"node":"8.17.0","npm":"6.13.4"})
npm WARN notsup Not compatible with your version of node/npm: @google-cloud/functions-framework@1.5.1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 309 packages from 559 contributors and audited 311 packages in 9.245s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Activated service account credentials for: [jenkins@nodejs-docs-samples-tests.iam.gserviceaccount.com]
Updated property [core/project].

> nodejs-docs-samples-functions-datastore@ test /tmpfs/src/github/nodejs-docs-samples/datastore/functions
> mocha test/*.test.js --timeout=5000


Error: Node.js v10.0.0 is a minimum requirement. To learn about legacy version support visit: https://github.com/googleapis/google-cloud-node#supported-nodejs-versions
    at new GrpcClient (/tmpfs/src/github/nodejs-docs-samples/datastore/functions/node_modules/google-gax/build/src/grpc.js:63:19)
    at Object.<anonymous> (/tmpfs/src/github/nodejs-docs-samples/datastore/functions/node_modules/@google-cloud/datastore/build/src/index.js:39:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmpfs/src/github/nodejs-docs-samples/datastore/functions/test/index.test.js:24:21)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at /tmpfs/src/github/nodejs-docs-samples/datastore/functions/node_modules/mocha/lib/mocha.js:349:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/tmpfs/src/github/nodejs-docs-samples/datastore/functions/node_modules/mocha/lib/mocha.js:346:14)
    at /tmpfs/src/github/nodejs-docs-samples/datastore/functions/node_modules/mocha/lib/mocha.js:382:12
    at new Promise (<anonymous>)
    at Mocha.loadFilesAsync (/tmpfs/src/github/nodejs-docs-samples/datastore/functions/node_modules/mocha/lib/mocha.js:381:12)
    at singleRun (/tmpfs/src/github/nodejs-docs-samples/datastore/functions/node_modules/mocha/lib/cli/run-helpers.js:149:15)
    at exports.runMocha (/tmpfs/src/github/nodejs-docs-samples/datastore/functions/node_modules/mocha/lib/cli/run-helpers.js:186:11)
    at Object.exports.handler (/tmpfs/src/github/nodejs-docs-samples/datastore/functions/node_modules/mocha/lib/cli/run.js:319:11)
    at innerArgv.then.argv (/tmpfs/src/github/nodejs-docs-samples/datastore/functions/node_modules/yargs/lib/command.js:241:49)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
npm ERR! Test failed.  See above for more details.


[ID: 6257229] Build finished after 56 secs, exit value: 1
```


<details>

**Comment by fhinkel** [comment]
Blocked by https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1855 for GAE and we want to hold off with an update in GCF.

**Comment by fhinkel** [comment]
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1886

**Comment by fhinkel** [comment]
fixed with https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1886
