### ISSUE TITLE
Can't install library. Fails with 404

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/nodejs-docs-samples#239]
Reposting from an internal bug, from a user following directions on:  

https://cloud.google.com/pubsub/docs/reference/libraries

Tried the install instructions but getting a 404

Cloud Pub/Sub
Cloud Pub/Sub Client Libraries

This page explains how to get started with Google Cloud Pub/Sub in your language of choice. Read more about client libraries for Cloud APIs in Client Libraries Explained.

Installing the Client Library

```
npm install --save @google-cloud/pubsub
```

```
npm install --save @google-cloud/pubsub
npm http GET https://registry.npmjs.org/google-cloud/pubsub
npm http 404 https://registry.npmjs.org/google-cloud/pubsub
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.19.0-69-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "@google-cloud/pubsub"
npm ERR! cwd /home/cloud/src/nodejs-docs-samples/appengine/pubsub
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/cloud/src/nodejs-docs-samples/appengine/pubsub/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jmdobry** [comment]
It's possible there was an issue with NPM when the user tried to install. I just tried to duplicate this and could not:

```
jdobry$ npm install --save @google-cloud/pubsub
> grpc@1.0.0 install /Users/jdobry/projects/test/node_modules/grpc
> node-pre-gyp install --fallback-to-build

[grpc] Success: "/Users/jdobry/projects/test/node_modules/grpc/src/node/extension_binary/grpc_node.node" is installed via remote
/Users/jdobry/projects/test
└─┬ @google-cloud/pubsub@0.4.0
  ├─┬ @google-cloud/common@0.7.0
  ├── arrify@1.0.1
  ├── extend@3.0.0
  ├─┬ google-gax@0.7.0
  ├── google-proto-files@0.8.3
  ├── is@3.1.0
  ├── modelo@4.2.0
  └── propprop@0.3.1
jdobry$
```
