### ISSUE TITLE
Speech sample: Error: spawn rec ENOENT with listen option

### ISSUE THREAD

**Issue by k33g** [GoogleCloudPlatform/nodejs-docs-samples#275]
Hello, I try the speech sample `recognize.js`, all options are ok except the `listen` option, I'm under OSX El Capitan with node 6.4.0.

```
node recognize.js listen
Listening, press Ctrl+C to stop.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn rec ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```

**Comment by k33g** [comment]
according #219 I've installed Sox `brew install sox`
no more error, but apparently nothing happens (it stops when I speak)
I have to understand the sample

**Comment by k33g** [comment]
ok it's fine, all is ok
