### ISSUE TITLE
SecurityCenter test failing due to exceeding buffer

### ISSUE THREAD

**Issue by kweinmeister** [GoogleCloudPlatform/nodejs-docs-samples#3146]
```
  1) Client with SourcesAndFindings
       client can list all findings:
     Error: spawnSync /bin/sh ENOBUFS
      at Object.spawnSync (node:internal/child_process:1119:20)
      at spawnSync (node:child_process:847:24)
      at execSync (node:child_process:927:15)
      at exec (system-test/v1/findings.test.js:21:21)
      at Context.<anonymous> (system-test/v1/findings.test.js:148:20)
      at processImmediate (node:internal/timers:466:21)
```

[Build log](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/actions/runs/4709336057/jobs/8352341106?pr=3143)

**Comment by kweinmeister** [comment]
Duplicate, closing
