### ISSUE TITLE
asset test getBatchEffectiveIamPolicies failing

### ISSUE THREAD

**Issue by kweinmeister** [GoogleCloudPlatform/nodejs-docs-samples#3417]
Blocks #3395, #3396, and #3400 
```
     Error: Command failed: node getBatchEffectiveIamPolicies //storage.googleapis.com/asset-nodejs-24bf8217-5aa2-4c94-b3b3-401f3a7473c0
5 NOT_FOUND: No resource found in resource search for <//storage.googleapis.com/asset-nodejs-24bf8217-5aa2-4c94-b3b3-401f3a7473c0> in requested scope <projects/long-door-651>; when searching resource hierarchy for <//storage.googleapis.com/asset-nodejs-24bf8217-5aa2-4c94-b3b3-401f3a7473c0>, please check the scope or the supported types in https://cloud.google.com/asset-inventory/docs/supported-asset-types#searchable_asset_types, and verify it has correct resource name format in https://cloud.google.com/asset-inventory/docs/resource-name-format.

      at checkExecSyncError (node:child_process:861:11)
      at Object.execSync (node:child_process:932:15)
      at execSync (test/iamPolicy.test.js:23:28)
      at Context.<anonymous> (test/iamPolicy.test.js:128:20)
      at processImmediate (node:internal/timers:466:21)
```

**Comment by rsamborski** [comment]
@Sita04 is this something you could address?

**Comment by Sita04** [comment]
Closing the issue as the last few [test runs](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/actions/runs/7945099174/job/21691328978) are successful.
