### ISSUE TITLE
sampleRate is not a field: undefined

### ISSUE THREAD

**Issue by muhammadsamir11** [GoogleCloudPlatform/nodejs-docs-samples#343]
I always getting this error 

lubuntu 16.04

google.cloud.speech.v1.RecognitionConfig#sampleRate is not a field: undefined

**Comment by jaumard** [comment]
Same for me on raspberry pi with minibian distrib
For log: 
```
Error: .google.cloud.speech.v1.RecognitionConfig#sampleRate is not a field: undefined
       at MessagePrototype.set (/var/www/sonus/node_modules/protobufjs/dist/protobuf.js:2490:35)
       at MessagePrototype.set (/var/www/sonus/node_modules/protobufjs/dist/protobuf.js:2483:38)
       at Message (/var/www/sonus/node_modules/protobufjs/dist/protobuf.js:2411:34)
       at Element.ProtoBuf.Reflect.ElementPrototype.verifyValue (/var/www/sonus/node_modules/protobufjs/dist/protobuf.js:1925:28)
       at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/var/www/sonus/node_modules/protobufjs/dist/protobuf.js:3499:33)
       at MessagePrototype.set (/var/www/sonus/node_modules/protobufjs/dist/protobuf.js:2493:59)
       at MessagePrototype.set (/var/www/sonus/node_modules/protobufjs/dist/protobuf.js:2483:38)
       at Message (/var/www/sonus/node_modules/protobufjs/dist/protobuf.js:2411:34)
       at Element.ProtoBuf.Reflect.ElementPrototype.verifyValue (/var/www/sonus/node_modules/protobufjs/dist/protobuf.js:1925:28)
       at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/var/www/sonus/node_modules/protobufjs/dist/protobuf.js:3499:33)
```
Node v7.9.0

**Comment by jmdobry** [comment]
The `sampleRate` field was recently renamed to `sampleRateHertz`. That's annoying I know, but the `@google-cloud/speech` client library has not yet reached `1.0.0`, so make sure to check [the changelog](https://github.com/GoogleCloudPlatform/google-cloud-node/releases) every time you upgrade. Here's [the release](https://github.com/GoogleCloudPlatform/google-cloud-node/releases/tag/speech-0.9.0) that contained the breaking change.
