### ISSUE TITLE
run/markdown-preview: test failure

### ISSUE THREAD

**Issue by subfuzion** [GoogleCloudPlatform/nodejs-docs-samples#3857]
Currently blocking: #3822 

Test fails [log](https://btx.cloud.google.com/invocations/34318311-12e3-46f7-abb7-5df05738e90d/targets/cloud-devrel%2Fnodejs-docs-samples%2Fpresubmit%2Frun%2Fmarkdown-preview-editor;config=default/log)

```
> markdown-preview-editor@0.0.1 test
> c8 mocha -p -j 2 test/app.test.js --timeout=10000 --exit

Error rendering markdown: Error: request to rendering service failed: Response code 405 (Method Not Allowed)
    at renderRequest (/tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/render.js:56:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/app.js:55:22
Error rendering markdown: Error: request to rendering service failed: Response code 405 (Method Not Allowed)
    at renderRequest (/tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/render.js:56:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/app.js:55:22
Error rendering markdown: Error: request to rendering service failed: Response code 405 (Method Not Allowed)
    at renderRequest (/tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/render.js:56:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/app.js:55:22
Error rendering markdown: Error: request to rendering service failed: Response code 405 (Method Not Allowed)
    at renderRequest (/tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/render.js:56:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/app.js:55:22
SyntaxError: Unexpected token s in JSON at position 0
    at JSON.parse ()
    at createStrictSyntaxError (/tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/node_modules/body-parser/lib/types/json.js:169:10)
    at parse (/tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/node_modules/body-parser/lib/types/json.js:86:15)
    at /tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/node_modules/body-parser/lib/read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (/tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/node_modules/raw-body/index.js:238:16)
    at done (/tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/node_modules/raw-body/index.js:227:7)
    at IncomingMessage.onEnd (/tmpfs/src/github/nodejs-docs-samples/run/markdown-preview/editor/node_modules/raw-body/index.js:287:7)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
-----------|---------|----------|---------|---------|-------------------
File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------|---------|----------|---------|---------|-------------------
All files  |   93.07 |    53.84 |     100 |   93.07 |                   
 app.js    |   91.17 |    57.14 |     100 |   91.17 | 35-36,44-46,56    
 render.js |   95.16 |       50 |     100 |   95.16 | 48-49,54          
-----------|---------|----------|---------|---------|-------------------
error: line 129 github/nodejs-docs-samples/.kokoro/build-with-run.sh


[ID: 9991002] Command finished after 155 secs, exit value: 1
```

**Comment by iennae** [comment]
fixed with #4201
