### ISSUE TITLE
Speech API: Error: spawn rec ENOENT with listen option 

### ISSUE THREAD

**Issue by thanigavel** [GoogleCloudPlatform/nodejs-docs-samples#397]
I am getting below error when listen command executed. 

Listening, press Ctrl+C to stop.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn rec ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3

**Comment by jonathandale** [comment]
Do you have sox installed?

`listen` — This command requires that you have SoX installed and available in your $PATH. See https://www.npmjs.com/package/node-record-lpcm16#dependencies

I just experienced the same and quickly installed with `brew install sox` (provided you use brew)
