### ISSUE TITLE
npm install & npm test is failing  on windows with speech sample

### ISSUE THREAD

**Issue by GH-rajasekharReddy** [GoogleCloudPlatform/nodejs-docs-samples#404]
I am new to nodejs. 

when doing "npm test" for speech sample, gettting the below error. 

running on windows and error details are given below, 

> > nodejs-docs-samples-speech@0.0.1 pretest E:\nodejs_voicer\nodejs-docs-samples\speech
> npm run lint

> nodejs-docs-samples-speech@0.0.1 lint E:\nodejs_voicer\nodejs-docs-samples\speech
> samples lint

lint: Linting files in: E:\nodejs_voicer\nodejs-docs-samples\speech
lint: Running: semistandard
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn semistandard ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rajbh\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v6.10.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-docs-samples-speech@0.0.1 lint: `samples lint`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs-docs-samples-speech@0.0.1 lint script 'samples lint'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nodejs-docs-samples-speech package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     samples lint
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nodejs-docs-samples-speech
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nodejs-docs-samples-speech
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\rajbh\AppData\Roaming\npm-cache\_logs\2017-06-19T12_05_07_367Z-debug.log
npm ERR! Test failed.  See above for more details.

> 

trying to install dependencies with "npm install" it failed.  Its error details are below, 

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

> 
appreciate the guidance.

**Comment by shahmirn** [comment]
Seeing the same issue in OSX high sierra for the helloworld function
