### ISSUE TITLE
Audio data is being streamed too fast or too slow 

### ISSUE THREAD

**Issue by shivag12** [GoogleCloudPlatform/nodejs-docs-samples#420]
Am facing an below issue when recording the audio from Microphone and streaming to the speech service,
I m able to get the text but after few seconds this below error comes up. 

{ Error: Audio data is being streamed too fast. Please stream audio data approximately at real time.
    at ClientDuplexStream._emitStatusIfDone (/home/pi/GoogleSpeechAPI/node_modules/grpc/src/node/src/client.js:270:19)
    at ClientDuplexStream._receiveStatus (/home/pi/GoogleSpeechAPI/node_modules/grpc/src/node/src/client.js:248:8)
    at /home/pi/GoogleSpeechAPI/node_modules/grpc/src/node/src/client.js:772:12
  code: 11,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Array] } } }

**Comment by livey0u** [comment]
@shivag12, I am also facing same issue. Were you able to find a resolution?
