### ISSUE TITLE
speech: improve error handling

### ISSUE THREAD

**Issue by broady** [GoogleCloudPlatform/nodejs-docs-samples#451]
Steps to reproduce:

```
$ cd nodejs-docs-samples/speech
$ node recognize.js sync recognize.js
ERROR: [TypeError: Cannot read property 'alternatives' of undefined]
```

(also note a healthy exit code)

**Comment by broady** [comment]
```
$ for i in $(seq 10); do cat resources/audio.raw resources/quit.raw; done > resources/big.raw
$ node recognize.js stream resources/big.raw
/usr/local/google/home/cbro/src/github.com/GoogleCloudPlatform/nodejs-docs-samples/speech/recognize.js:383
          `Transcription: ${data.results[0].alternatives[0].transcript}`);
                                           ^

TypeError: Cannot read property 'alternatives' of undefined
    at null.<anonymous> (/usr/local/google/home/cbro/src/github.com/GoogleCloudPlatform/nodejs-docs-samples/speech/recognize.js:383:44)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at addChunk (/usr/local/google/home/cbro/src/github.com/GoogleCloudPlatform/nodejs-docs-samples/speech/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/usr/local/google/home/cbro/src/github.com/GoogleCloudPlatform/nodejs-docs-samples/speech/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at Readable.push (/usr/local/google/home/cbro/src/github.com/GoogleCloudPlatform/nodejs-docs-samples/speech/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at Duplexify._forward (/usr/local/google/home/cbro/src/github.com/GoogleCloudPlatform/nodejs-docs-samples/speech/node_modules/duplexify/index.js:163:26)
    at DestroyableTransform.onreadable (/usr/local/google/home/cbro/src/github.com/GoogleCloudPlatform/nodejs-docs-samples/speech/node_modules/duplexify/index.js:127:10)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
Exit code 1
```
