### ISSUE TITLE
error ECONNREFUSED

### ISSUE THREAD

**Issue by tommy2049** [GoogleCloudPlatform/nodejs-docs-samples#523]
I followed this tutorial https://cloud.google.com/appengine/docs/flexible/nodejs/using-cloud-sql and reread the material about 10 times. Made sure I had my proxy running. When I run createtables.js I get the following error. It's not descriptive of why the server is refusing the conncetion.

Failed to create 'visits' table: { Error: connect ECONNREFUSED 127.0.0.1:5432
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1175:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432 }

**Comment by mikeInkerz** [comment]
I'm running into the same issue, how did you solve that?
